use_frameworks!

platform :ios, '8.0'

target 'PYKLogining_Example' do
  pod 'PYKLogining', :path => '../'
  pod 'PYKNetworking', :path => '../../PYKNetworking'
  
  

  target 'PYKLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
